version: '3.7'

services:
  data-input-api:
    build:
      context: ./src/data-input-api
    ports:
      - "6001:8000"
    networks:
      - local-network
  
  data-output-api:
    build:
      context: ./src/data-output-api
    ports:
      - "6002:8000"
    networks:
      - local-network

  data-robot:
    build:
      context: ./src/data-robot
    networks:
      - local-network

  mongo:
    image: mongo:latest
    ports:
     - "27061:27061"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
     - local-network
    volumes:
      - mongodata:/data/db

networks:
  local-network:
    driver: bridge
    attachable: true

volumes:
  mongodata: